# Generated by Django 6.1.1 on 2026-09-09 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PercepcionEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion', models.CharField(choices=[('feliz', 'Feliz / contento'), ('motivado', 'Motivado / con energía'), ('tranquilo', 'Tranquilo'), ('estresado', 'Preocupado / estresado'), ('triste', 'Desanimado / triste'), ('agotado', 'Agotado / con poca energía'), ('malestar', 'Con malestar físico'), ('otro', 'Otro')], max_length=30)),
                ('necesita_apoyo', models.BooleanField(default=False)),
                ('tipo_apoyo', models.CharField(choices=[('ninguno', 'No necesito apoyo'), ('lider', 'Conversar con mi líder'), ('rrhh', 'Recibir orientación de RR.HH.'), ('prevencion', 'Recibir orientación de Prevención')], default='ninguno', max_length=30)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percepciones_emocionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Percepción emocional',
                'verbose_name_plural': 'Percepciones emocionales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaPES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_pes', models.BooleanField(verbose_name='¿Se identifica como persona especialmente sensible?')),
                ('condicion', models.CharField(blank=True, choices=[('embarazo', 'Embarazo'), ('lactancia', 'Periodo de lactancia'), ('discapacidad', 'Discapacidad física, cognitiva o sensorial'), ('adulto_mayor', 'Persona adulta mayor'), ('adolescente', 'Adolescente con edad para trabajar'), ('perimenopausia', 'Perimenopausia'), ('menopausia', 'Menopausia'), ('menstrual', 'Periodo menstrual'), ('otra', 'Otra condición'), ('prefiero_no_indicar', 'Prefiero no especificar')], max_length=50)),
                ('necesita_apoyo', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_pes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta PES',
                'verbose_name_plural': 'Respuestas PES',
                'ordering': ['-fecha'],
            },
        ),
    ]
