# Generated by Django 6.1.1 on 2026-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percepcionemocional',
            name='necesita_apoyo',
        ),
        migrations.AddField(
            model_name='percepcionemocional',
            name='acciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='percepcionemocional',
            name='emocion',
            field=models.CharField(choices=[('feliz', 'Feliz / contento(a)'), ('motivado', 'Motivado(a) / con energía'), ('tranquilo', 'Tranquilo(a)'), ('estresado', 'Preocupado(a) / estresado(a)'), ('triste', 'Desanimado(a) / triste'), ('agotado', 'Agotado(a) / con poca energía'), ('malestar', 'Con malestar físico / enfermo(a)'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='percepcionemocional',
            name='tipo_apoyo',
            field=models.CharField(choices=[('ninguno', 'No necesito apoyo'), ('manager', 'Manager / Líder'), ('rrhh', 'RR.HH.'), ('prevencion', 'Prevención de Riesgos'), ('otro', 'Otro')], default='ninguno', max_length=30),
        ),
        migrations.AlterField(
            model_name='respuestapes',
            name='condicion',
            field=models.CharField(blank=True, choices=[('embarazo', 'Embarazo'), ('lactancia', 'Período de lactancia'), ('discapacidad', 'Discapacidad física, cognitiva o sensorial'), ('adulto_mayor', 'Persona adulta mayor'), ('adolescente', 'Adolescente con edad para trabajar'), ('perimenopausia', 'Perimenopausia'), ('menopausia', 'Menopausia'), ('menstrual', 'Período menstrual'), ('otra', 'Otra condición'), ('prefiero_no_indicar', 'Prefiero no especificar')], max_length=50),
        ),
    ]
