# Generated by Django 6.1.1 on 2026-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0002_remove_percepcionemocional_necesita_apoyo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percepcionemocional',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='percepcionemocional',
            name='momento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], default='entrada', max_length=10),
        ),
    ]
