# Generated by Django 6.1.1 on 2026-09-10 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0003_alter_percepcionemocional_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percepcionemocional',
            options={'ordering': ['-fecha'], 'verbose_name': 'Percepción emocional', 'verbose_name_plural': 'Percepciones emocionales'},
        ),
        migrations.CreateModel(
            name='SolicitudApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('atendida', 'Atendida')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_atendidas', to=settings.AUTH_USER_MODEL)),
                ('percepcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='bienestar.percepcionemocional')),
            ],
            options={
                'verbose_name': 'Solicitud de apoyo',
                'verbose_name_plural': 'Solicitudes de apoyo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AtencionApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('contacto', 'Contacto realizado'), ('conversacion', 'Conversación con trabajador'), ('seguimiento', 'Seguimiento'), ('derivacion', 'Derivación'), ('ajuste', 'Medida / ajuste implementado'), ('orientacion', 'Orientación entregada'), ('cierre', 'Cierre de solicitud'), ('otro', 'Otro')], max_length=30)),
                ('comentario', models.TextField()),
                ('estado_resultante', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('atendida', 'Atendida')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_atencion', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='bienestar.solicitudapoyo')),
            ],
            options={
                'verbose_name': 'Atención de apoyo',
                'verbose_name_plural': 'Atenciones de apoyo',
                'ordering': ['-fecha'],
            },
        ),
    ]
