# Generated by Django 5.2.17 on 2026-09-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bienestar", "0004_alter_percepcionemocional_options_solicitudapoyo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="respuestapes",
            name="identidad_sexogenerica",
            field=models.CharField(
                blank=True,
                choices=[
                    ("femenino", "Femenino"),
                    ("masculino", "Masculino"),
                    ("otro", "Otro"),
                    ("prefiero_no_decirlo", "Prefiero no decirlo"),
                ],
                max_length=30,
                null=True,
                verbose_name="Identidad sexogenérica",
            ),
        ),
        migrations.AlterField(
            model_name="respuestapes",
            name="condicion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("embarazo", "Embarazo"),
                    ("lactancia", "Período de lactancia"),
                    ("discapacidad", "Discapacidad física, cognitiva o sensorial"),
                    ("adulto_mayor", "Persona adulta mayor"),
                    ("adolescente", "Adolescente con edad para trabajar"),
                    ("perimenopausia", "Perimenopausia"),
                    ("menopausia", "Menopausia"),
                    ("periodo_menstrual", "Menstruación Dolorosa (Dismenorrea)"),
                    ("otra", "Otra condición"),
                    ("prefiero_no_indicar", "Prefiero no especificar"),
                ],
                max_length=50,
            ),
        ),
    ]
